version: "3.8"
services:
  postgres:
    image: postgres:alpine
    network_mode: bridge
    container_name: momentum-postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=momentum-postgres-db
    restart: unless-stopped
  # REST API app
  app:
    image: momentum/momentum-app
    network_mode: bridge
    container_name: momentum-app
    expose:
      - 8080
    ports:
      - 8080:8080
    volumes:
      - /home/admin01/dev:/var/tmp
    restart: unless-stopped

  pgadmin:
    container_name: momemtum-pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: wanted.lepota@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "82:80"
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  kafka:
      image: confluentinc/cp-kafka:latest
      depends_on:
        - zookeeper
      ports:
        - 29092:29092
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
volumes:
  postgres-data:

