CREATE TABLE IF NOT EXISTS person (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	name varchar(255) not null,
	surname varchar(255) not null,
	gender varchar(255) not null,
	identitynumber varchar(255) not null,
	dateofbirth varchar(255) not null,
	age INTEGER,
	PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS product (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	name varchar(255) not null,
	type varchar(255) not null,
	balance decimal( 10, 2 ) not null,
	PRIMARY KEY (id)
);

CREATE TABLE person_product (
  product_id INT
 , person_id INT
 ,CONSTRAINT person_product PRIMARY KEY (product_id, person_id )
 ,CONSTRAINT FK_person
  FOREIGN KEY (person_id) REFERENCES person (id)
 ,CONSTRAINT FK_product
  FOREIGN KEY (product_id) REFERENCES product (id)
);

CREATE TABLE IF NOT EXISTS address (
    id bigint not null
    , address_line1 varchar(255)
    , address_line2 varchar(255)
    , address_line3 varchar(255)
    , address_type varchar(255)
    , city varchar(255)
    , postal_code varchar(255)
    , preffered_address varchar(255)
    , province varchar(255)
    , primary key (id)
    );

CREATE TABLE IF NOT EXISTS bank_details (
    id bigint not null
    , account_number varchar(255)
    , account_type varchar(20)
    , bank_name varchar(255)
    , branchcode varchar(255)
    , person_id integer
    , primary key (id)
    );

CREATE TABLE IF NOT EXISTS contact (
    id bigint not null
    , cellphone_no varchar(255)
    , email_address varchar(255)
    , preferred_contact_method varchar(255)
    , telephone_number varchar(255)
    , primary key (id)
    );

--create table withdrawal (id bigint not null, created_by varchar(255), created_date timestamp(6), last_mod_date timestamp(6), modified_by varchar(255), investor_id varchar(255), product_id varchar(255), status varchar(255), "withdrawal-amount" numeric(38,2), primary key (id))