CREATE TABLE IF NOT EXISTS PRODUCT (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	name varchar(255) not null,
	type varchar(255) not null,
	balance decimal( 10, 2 ) not null
);

create sequence person_sequence start with 1 increment by 1;

insert into PRODUCT (name, type, balance) values ('product1', 'retirement',500000.00),
                                                        ('product2', 'savings',36000.00);
                                                        
