CREATE TABLE IF NOT EXISTS person (
	person_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	name varchar(255) not null,
	surname varchar(255) not null,
	gender varchar(255) not null,
	identitynumber varchar(255) not null,
	dateofbirth varchar(255) not null,
	age INTEGER,
	PRIMARY KEY (person_id)
);

CREATE TABLE IF NOT EXISTS product (
	product_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	name varchar(255) not null,
	type varchar(255) not null,
	balance decimal( 10, 2 ) not null,
	PRIMARY KEY (product_id)
);

CREATE TABLE person_product (
  person_id INT
 ,product_id INT
 ,CONSTRAINT person_product PRIMARY KEY (person_id, product_id)
 ,CONSTRAINT FK_person
  FOREIGN KEY (person_id) REFERENCES person (person_id)
 ,CONSTRAINT FK_product
  FOREIGN KEY (product_id) REFERENCES product (product_id)
);

INSERT INTO person
      (person_id, name, surname, gender, identitynumber, dateofbirth, age)
      VALUES(1, 'Tshepo', 'Khumalo', 'Male', '8201315548083', '19820430', 40),
            (2, 'Jacqueline', 'Cruise', 'Female', '9204295548083', '19920429', 30);

INSERT INTO product
      (product_id, name, type, balance)
      VALUES (1, 'product1', 'RETIREMENT',500000.00),
             (2, 'product2', 'SAVINGS',30000.00);

