CREATE TABLE IF NOT EXISTS person (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	firstName varchar(255) not null,
	surname varchar(255) not null,
	gender varchar(255) not null,
	identityNumber varchar(255) not null,
	dateOfBirth varchar(255) not null,
	age INTEGER
);
/*
 one-to-many: Person has many products
*/
CREATE TABLE product (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	name varchar(255) not null,
	type varchar(255) not null,
	balance decimal( 10, 2 ) not null
	PRIMARY KEY (id),
      FOREIGN KEY (person_id)
          REFERENCES person(id)
          ON DELETE CASCADE
);
/*
 one-to-many: Person has many contacts
*/
CREATE TABLE contact (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	cellPhoneNo varchar(255) not null,
	emailAddress varchar(255) not null,
    preferredContactMethod varchar(255),
    telephoneNumber varchar(255)
	PRIMARY KEY (id),
      FOREIGN KEY (person_id)
          REFERENCES person(id)
          ON DELETE CASCADE
);

/*
 one-to-many: Person has many contacts
*/
CREATE TABLE address (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	addressLine1 varchar(255) not null,
	addressLine2 varchar(255) not null,
	addressLine3 varchar(255) not null,
    addressType varchar(255),
    postalCode varchar(255),
    city varchar(255)
	PRIMARY KEY (id),
      FOREIGN KEY (person_id)
          REFERENCES person(id)
          ON DELETE CASCADE
);

/*
 one-to-many: Person has one bank details
*/
CREATE TABLE bankDetails (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	accountNumber varchar(255) not null,
	accountType varchar(255) not null,
	bankName varchar(255) not null,
    code varchar(255),
	PRIMARY KEY (id),
      FOREIGN KEY (person_id)
          REFERENCES person(id)
          ON DELETE CASCADE
);

INSERT INTO person
      (id, firstName, surname, gender, identityNumber, dateOfBirth, age)
      VALUES('Wanted', 'Lepota', 'Male', '8204305548083', '19820430', 40),
            ('Jacqueline', 'Cruise', 'Female', '9204295548083', '19920429', 30)

INSERT INTO product
      (id,name, type, balance)
      VALUES (1,'product1', 'RETIREMENT',500000.00),
             (2,'product2', 'SAVINGS',30000.00);

INSERT INTO contact
      (id,cellPhoneNo, emailAddress, preferredContactMethod, telephoneNumber)
      VALUES (1,'0831230000', 'e@etalente.co.za','cellphone','0121230000');

INSERT INTO address
      (id,addressLine1, addressLine2, addressLine3, addressType, postalCode, city)
      VALUES (1,'123', 'kamo street','randburg','residential', '2010', 'Leswikiswiki');

INSERT INTO bankDetails
      VALUES (1,'6212345000', 'cheque','teba bank', '25062');

